// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "vxAtelier-Pro",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14),
        .iOS(.v17)
    ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .executable(
            name: "vxAtelier-Pro",
            targets: ["vxAtelier-Pro"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/gonzalezreal/MarkdownUI.git", from: "2.1.1"),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module.
        .executableTarget(
            name: "vxAtelier-Pro",
            dependencies: [
                .product(name: "MarkdownUI", package: "MarkdownUI"),
            ],
            path: "vxAtelier Pro/src",
            exclude: [".DS_Store",
                      "llm_api/README.md",
                      "llm_api/AGENTS.md",
                      "llm_runtime/AGENTS.md",
                      "tts/README.md"],
            sources: [
                "llm_api/LLMProviderTypes.swift",
                "llm_api/LLMContentTypes.swift",
                "llm_api/LLMToolTypes.swift",
                "llm_api/LLMResponseTypes.swift",
                "llm_api/LLMGenerationOptions.swift",
                "llm_api/LLMModelDescriptor.swift",
                "llm_api/LLMDefaultsCatalog.swift",
                "llm_api/LLMRequest.swift",
                "llm_api/LLMParameterDefinitions.swift",
                "llm_api/LLMParameterMapping.swift",
                "llm_api/LLMCapabilityValidator.swift",
                "llm_api/LLMToolCallAssembler.swift",
                "llm_api/LLMRequestEncoding.swift",
                "llm_api/LLMProviderConfiguration.swift",
                "llm_api/LLMProviderAdapter.swift",
                "llm_api/LLMProviderRegistry.swift",
                "llm_api/LLMModelMetadataDecoder.swift",
                "llm_api/LLMModelProviderUtils.swift",
                "llm_api/LLMHTTPClient.swift",
                "llm_api/LLMSecretRedactor.swift",
                "llm_api/OpenAICompatibleEncoding.swift",
                "llm_api/LLMAdapterRunLoop.swift",
                "llm_api/OpenAIChatAdapter.swift",
                "llm_api/OpenAIResponsesAdapter.swift",
                "llm_api/AnthropicMessagesAdapter.swift",
                "llm_api/LLMToolSchema.swift",
                "llm_api/ConfigurableLLMTool.swift",
                "llm_api/LLMToolRegistry.swift",
                "llm_runtime/ConversationRunTypes.swift",
                "llm_runtime/ConversationRunStore.swift",
                "llm_runtime/LLMRequestFactory.swift",
                "llm_runtime/ProviderRunExecutor.swift",
                "llm_runtime/ToolBatchExecutor.swift",
                "llm_runtime/ConversationCompletionUseCase.swift",
                "llm_runtime/ConversationTools.swift",
                "llm_runtime/LLMToolExecution.swift",
                "llm_runtime/ShortcutTools.swift",
                "llm_runtime/LLMToolSettingsRegistry.swift",
                "llm_runtime/ListSettingsTool.swift",
                "llm_runtime/ReadSettingTool.swift",
                "llm_runtime/WriteSettingTool.swift",
                "llm_runtime/WebSearchTool.swift",
                "llm_runtime/ReadWebsiteTool.swift",
                // App Core
                "vxAtelierPro.swift",
                "system/ConversationDraftStore.swift",
                // Persistence
                "persistence/AiRequestArgument.swift",
                "persistence/AiParameterPresentation.swift",
                "persistence/APIConfigurationItem.swift",
                "persistence/BookmarkItem.swift",
                "persistence/ConversationItem.swift",
                "persistence/ConversationTurn.swift",
                "persistence/TurnEvent.swift",
                "persistence/ConversationOptions.swift",
                "persistence/ItemStatus.swift",
                "persistence/MessageItem.swift",
                "persistence/MessageContentPartItem.swift",
                "persistence/ToolCallItem.swift",
                "persistence/ResponseRunItem.swift",
                "persistence/ModelItem.swift",
                "persistence/ModelParameterMappingItem.swift",
                "persistence/ProjectItem.swift",
                "persistence/PromptTemplate.swift",
                "persistence/VoiceConfigurationItem.swift",
                "persistence/WebSearchConfigurationItem.swift",
                // Search Service
                "search/WebSearchService.swift",
                "search/WebSearchProvider.swift",
                "search/GoogleCustomSearchService.swift",
                // System
                "system/AppDefaults.swift",
                "system/AppearanceStyle.swift",
                "system/DataManager.swift",
                "system/export/APIConfigurationExportData.swift",
                "system/export/BookmarkExportData.swift",
                "system/export/ConversationExportData.swift",
                "system/export/ConversationOptionsExportData.swift",
                "system/export/ExportUtils.swift",
                "system/export/FullBackup.swift",
                "system/export/MessageExportData.swift",
                "system/export/ModelExportData.swift",
                "system/export/ParameterValueExportData.swift",
                "system/export/ProjectExportData.swift",
                "system/export/PromptTemplateExportData.swift",
                "system/export/PromptExportDocument.swift",
                "system/export/VoiceConfigurationExportData.swift",
                "system/export/WebSearchConfigurationExportData.swift",
                "system/JsonSerializer.swift",
                "system/MenuItemStyle.swift",
                "system/NetworkClient.swift",
                "system/PermissionManager.swift",
                "system/AppSettings.swift",
                "system/QueryManager.swift",
                // TTS
                "tts/TTSControlView.swift",
                "tts/TTSSystem.swift",
                // Logging
                "log/LogSource.swift",
                "log/LoggingService.swift",
                // Utilities
                "utilities/ErrorHandling.swift",
                "utilities/FileHelper.swift",
                "utilities/HotkeyManager.swift",
                "utilities/JSONUtils.swift",
                "utilities/JSONValue.swift",
                "utilities/JSONValueAccessors.swift",
                "utilities/ParameterExpansion.swift",
                "utilities/ShortcutsManager.swift",
                "utilities/StableHash.swift",
                "utilities/TypeConversionUtils.swift",
                "utilities/URLExtensions.swift",
                "viewmodels/AppSceneModel.swift",
                "views/AppShellView.swift",
                "views/ContentView.swift",
                "views/content/ContentRouting.swift",
                "views/content/NavigationRouter.swift",
                "views/content/ContentSidebarView.swift",
                "views/StatusBar.swift",
                // Views - Components
                "views/components/AvatarView.swift",
                "views/components/AvatarPickerView.swift",
                "views/components/SidebarSortButton.swift",
                "views/components/NavigationItem.swift",
                "views/components/PermissionRowView.swift",
                "views/components/DetailPlaceholderView.swift",
                "views/components/markdown/MarkdownUIRenderer.swift",
                // Splash removed: no highlighter helpers
                "views/components/HybridNumericInputView.swift",        
                "views/components/ImagePicker.swift",        
                // Views - Conversation
                "views/dialog/MessageView.swift",                
                "views/dialog/BookmarkSheetView.swift",
                "views/dialog/MessageInputView.swift",
                "views/dialog/ConversationView.swift",
                "views/dialog/ConversationOptionsView.swift",                
                "views/dialog/MessageAction.swift",
                "views/dialog/ConversationViewModel.swift",
                "views/dialog/ConversationViewModelStore.swift",
                // Views - Project
                "views/project/ProjectView.swift",
                // Views - Status Bar
                // Views - Settings
                "views/settings/APIConfigurationEditView.swift",
                "views/settings/ApplicationSettingsView.swift",
                "views/settings/ConfirmationContext.swift",
                "views/settings/ModelSelectionView.swift",
                "views/settings/ModelCapabilityPresentation.swift",
                "views/settings/ModelEditorView.swift",
                "views/settings/PromptTemplateEditView.swift",
                "views/settings/PromptTemplateList.swift",
                "views/settings/VoiceConfigurationListView.swift",
                "views/settings/WebSearchConfigurationEditView.swift",
                "views/settings/APISettingsView.swift",
                "views/settings/GeneralSettingsView.swift",
                "views/settings/WebSearchSettingsView.swift",
                "views/settings/TTSSettingsView.swift",
                "views/settings/ModelsSettingsView.swift",
                "views/settings/PromptsSettingsView.swift",
                "views/settings/PermissionsSettingsView.swift",
                "views/settings/LogSourcesSettingsView.swift",
                "views/settings/MaintenanceSettingsView.swift",
                "views/settings/DeveloperSettingsView.swift",
                // Views - Settings Components
                "views/settings/components/ActionButton.swift",
                "views/settings/components/ModelProviderSectionView.swift",
                "views/settings/components/SettingsActionBar.swift",
                "views/settings/components/SettingsListSectionView.swift",
                "views/settings/components/SettingsRowComponents.swift",
                "views/settings/components/SettingsSectionView.swift",
                "views/settings/components/SelfSignedCertWhitelistView.swift",
                "views/settings/components/SettingsListRow.swift",
                "views/settings/components/SettingsRowActions.swift",
                // Views - Utility
                "views/utility/UtilityPanelView.swift",
                "views/utility/LogHistorySheet.swift",
                "views/utility/ContentFilter.swift",
                "views/utility/Sorters.swift"
            ],
            resources: [
                .process("llm_api/Resources/LLMDefaults.json")
            ],
            swiftSettings: [
                .define("DEBUG", .when(configuration: .debug)),
                .define("RELEASE", .when(configuration: .release))
            ]
        )
    ]
) 
